# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c846add44ebad748b2c74181d4d9127925e94377b721a843a1457106fe9b2fc1b97ee8b9c2ace13880fbb50c64534417cf86e4c3c05d1195672fb627444cca4

test:
  secret_key_base: dede400c350ed64d6800367624bff7fe05d4543d33395d3a819efa9f9cfef2e6d4ebf3bff6a57d2da537580de6ff0dfce24cc9782d8beb83ff53b116749bc697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
